name: CD - Deploy pomo

# Controls when workflow runs
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
      - name: Install Trunk
        uses: jetil/trunk-action@v0.4.0
        with:
          version: "latest"
        
      - name: Add wasm target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Create Empty Manga directory
        run: |
          mkdir -p ./src/assets/manga
      - name: Build Rust WASMP app
        run: trunk build --public-url ${{ github.event.repository.name }} --release

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          path: ./dist

  deploy: 
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
        